'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import ArticlesList from '@/components/ArticlesList';
import { articlesAPI } from '@/lib/api';
import { getCurrentUser, isAuthenticated } from '@/lib/auth';
import { Article } from '@/types';

export default function ArticlesPage() {
  const router = useRouter();
  const [articles, setArticles] = useState<Article[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    if (!isAuthenticated()) {
      router.push('/login');
      return;
    }

    const currentUser = getCurrentUser();
    setUser(currentUser);

    if (currentUser?.tenantId) {
      loadArticles(currentUser.tenantId);
    }
  }, [router]);

  const loadArticles = async (tenantId: string) => {
    try {
      // Mock articles data (replace with actual API call)
      const mockArticles: Article[] = [
        {
          id: '1',
          clusterId: 'cluster_123',
          title: 'The Ultimate Guide to Digital Marketing in 2025',
          content: 'Full article content...',
          wordpressUrl: 'https://example.com/digital-marketing-guide-2025',
          wordpressId: 1001,
          publishedAt: new Date(Date.now() - 172800000).toISOString(),
          metadata: {
            keywords: [
              'digital marketing',
              'online marketing strategy',
              'marketing automation',
            ],
            wordCount: 2847,
            featuredImageUrl: 'https://example.com/image1.jpg',
          },
        },
        {
          id: '2',
          clusterId: 'cluster_124',
          title: 'SEO Best Practices for E-commerce Websites',
          content: 'Full article content...',
          wordpressUrl: 'https://example.com/seo-ecommerce-best-practices',
          wordpressId: 1002,
          publishedAt: new Date(Date.now() - 432000000).toISOString(),
          metadata: {
            keywords: [
              'SEO best practices',
              'e-commerce SEO',
              'product page optimization',
            ],
            wordCount: 3124,
            featuredImageUrl: 'https://example.com/image2.jpg',
          },
        },
        {
          id: '3',
          clusterId: 'cluster_125',
          title: 'How to Build a Content Marketing Strategy That Works',
          content: 'Full article content...',
          wordpressUrl: 'https://example.com/content-marketing-strategy',
          wordpressId: 1003,
          publishedAt: new Date(Date.now() - 691200000).toISOString(),
          metadata: {
            keywords: [
              'content marketing strategy',
              'content planning',
              'content calendar',
            ],
            wordCount: 2956,
            featuredImageUrl: 'https://example.com/image3.jpg',
          },
        },
      ];

      setArticles(mockArticles);
    } catch (error) {
      console.error('Error loading articles:', error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">
            Published Articles
          </h1>
          <p className="mt-2 text-gray-600">
            All articles generated by WF3 and published to WordPress
          </p>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="bg-white rounded-lg shadow border border-gray-200 p-6">
            <p className="text-sm font-medium text-gray-600">Total Articles</p>
            <p className="mt-2 text-3xl font-semibold text-gray-900">
              {articles.length}
            </p>
          </div>
          <div className="bg-white rounded-lg shadow border border-gray-200 p-6">
            <p className="text-sm font-medium text-gray-600">This Week</p>
            <p className="mt-2 text-3xl font-semibold text-gray-900">
              {
                articles.filter(
                  (a) =>
                    new Date(a.publishedAt) >
                    new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
                ).length
              }
            </p>
          </div>
          <div className="bg-white rounded-lg shadow border border-gray-200 p-6">
            <p className="text-sm font-medium text-gray-600">Avg. Word Count</p>
            <p className="mt-2 text-3xl font-semibold text-gray-900">
              {articles.length > 0
                ? Math.round(
                    articles.reduce(
                      (sum, a) => sum + (a.metadata?.wordCount || 0),
                      0
                    ) / articles.length
                  ).toLocaleString()
                : 0}
            </p>
          </div>
        </div>

        {/* Articles List */}
        <ArticlesList articles={articles} isLoading={isLoading} />

        {/* Info */}
        <div className="mt-8 bg-blue-50 border border-blue-200 rounded-lg p-4">
          <h3 className="text-sm font-medium text-blue-900 mb-2">
            ℹ️ About Article Generation
          </h3>
          <p className="text-sm text-blue-800">
            Articles are automatically generated every Monday and Thursday at
            8:00 AM by WF3. Each article is 2000+ words, SEO-optimized with
            featured images, and published directly to your WordPress site. The
            system picks the next pending cluster and generates a comprehensive
            article based on the clustered keywords.
          </p>
        </div>
      </div>
    </div>
  );
}
